spring:
  thymeleaf:
    cache: false
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/security?characterEncoding=UTF-8&useSSL=false
    username: root
    password: root
mybatis:
  type-aliases-package: com.yetong.entity
  mapper-locations: classpath:mapper/*.xml
logging:
  level:
    com:
      yetong: debug
server:
  reactive:
    session:
      timeout: 1
mybatis-plus:
  type-aliases-package: com.yetong.entity
# token配置
token:
  # 令牌自定义标识
  header: Authorization
  # 令牌密钥
  secret: V9RlaFCwZfxQ#PLJxRfKGU0IGNZKP7Kq
  # 令牌有效期（默认30分钟）
  expireTime: 1800

